# Docker deployment made for active development

version: "3"
services:
  db:
    container_name: mongo
    image: mongo
    restart: on-failure
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: stg-api
    depends_on:
      - 'db'
    restart: always
    build: ../FHNW-SQL-Training-Game-API
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stg-api
      - JWT_SECRET=FHNW_2021
      - FROM_SENDER=stg@github.io                                 # Necessary env. variable on prod.
      - POSTMARK_API_KEY=blank
      - PORT=3001
      - IO_URL=http://localhost:80                                # Necessary env. variable on prod.
    ports:
      - "3001:3001"
  frontend:
    container_name: stg-frontend
    depends_on:
      - 'api'
    restart: always
    build:
      context: .                                                  # Use local directory for building process
      args:
        API_URL: http://localhost:3000                            # Necessary env. variable on prod.
        API_URL_PUBLIC: ${API_URL_PUBLIC}
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ../FHNW-SQL-Training-Game.github.io:/usr/share/nginx/html  # Mounting of frontend code
