# Docker deployment made for active development

services:
  db:
    container_name: stg-mongo
    image: mongo
    restart: on-failure
    volumes:
      - mongo-data:/data/db                                       # Use named volume
    ports:
      - "27017:27017"

  api:
    container_name: stg-api
    depends_on:
      - db
    restart: always
    build: ../FHNW-SQL-Training-Game-API
    environment:
      - MONGODB_URI=mongodb://stg-mongo:27017/stg-api
      - JWT_SECRET=FHNW_2021
      - FROM_SENDER=stg@github.io                                 # Necessary env. variable on prod.
      - POSTMARK_API_KEY=blank
      - PORT=4001
      - IO_URL=http://localhost:80                                # Necessary env. variable on prod.
    ports:
      - "4001:4001"

  frontend:
    container_name: stg-frontend
    depends_on:
      - api
    restart: always
    build:
      context: .                                                  # Use local directory for building process
      args:
        API_URL: http://localhost:4001                            # Necessary env. variable on prod.
        API_URL_PUBLIC: ${API_URL_PUBLIC}
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ../FHNW-SQL-Training-Game.github.io:/usr/share/nginx/html  # Mounting of frontend code

  model:
    container_name: stg-model
    restart: always
    build:
      context: .
      dockerfile: model/Dockerfile
      args:
        API_URL: http://localhost:4001
    environment:
      - MONGODB_URI=mongodb://stg-mongo:27017/stg-api
    ports:
      - "5001:5001"

volumes:
  mongo-data:
