@host = localhost:4000
#@host = fhnw-sql-training-game-api.herokuapp.com/

POST http://{{host}}/users/register  HTTP/1.1
content-type: application/json

{
    "username": "stg@github.io",
    "password": "123456"
}

###

# @name auth
POST http://{{host}}/users/authenticate  HTTP/1.1
content-type: application/json

{
    "username": "stg@github.io",
    "password": "123456"
}

###

GET http://{{host}}/users/self  HTTP/1.1
content-type: application/json
Authorization: Bearer {{auth.response.body.token}}


###

PATCH http://{{host}}/users/self/answer_sql  HTTP/1.1
content-type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
    "course": 1,
    "task": 3,
    "correct": true,
    "query": "SELECT * FROM DE"
}