@host = localhost:4000
#@host = fhnw-sql-training-game-api.herokuapp.com/

POST http://{{host}}/users/register  HTTP/1.1
content-type: application/json

{
    "username": "kai.krause@students.fhnw.ch",
    "password": "123456"
}

###

POST http://{{host}}/users/recover  HTTP/1.1
content-type: application/json

{
    "username": "kai.krause@students.fhnw.ch"
}

###

POST http://{{host}}/users/reset  HTTP/1.1
content-type: application/json

{
    "token": "7ba4e781dac1f00254b04b0e3f9a92cd790a276e",
    "password": "123456"
}

###

# @name auth
POST http://{{host}}/users/authenticate  HTTP/1.1
content-type: application/json

{
    "username": "kai.krause@students.fhnw.ch",
    "password": "123456"
}

###

GET http://{{host}}/users/self  HTTP/1.1
content-type: application/json
Authorization: Bearer {{auth.response.body.token}}


###

PATCH http://{{host}}/users/self/answer_sql  HTTP/1.1
content-type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
    "task": "task-2",
    "correct": true,
    "query": "SELECT * FROM Lorem"
}